// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Cinema is the predicate function for cinema builders.
type Cinema func(*sql.Selector)

// Movie is the predicate function for movie builders.
type Movie func(*sql.Selector)

// Screening is the predicate function for screening builders.
type Screening func(*sql.Selector)

// Seat is the predicate function for seat builders.
type Seat func(*sql.Selector)

// SeatReservation is the predicate function for seatreservation builders.
type SeatReservation func(*sql.Selector)
