// Code generated by ent, DO NOT EDIT.

package cinema

import (
	"cinema/pkg/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Cinema {
	return predicate.Cinema(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Cinema {
	return predicate.Cinema(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Cinema {
	return predicate.Cinema(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Cinema {
	return predicate.Cinema(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Cinema {
	return predicate.Cinema(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Cinema {
	return predicate.Cinema(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Cinema {
	return predicate.Cinema(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Cinema {
	return predicate.Cinema(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Cinema {
	return predicate.Cinema(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Cinema {
	return predicate.Cinema(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Cinema {
	return predicate.Cinema(sql.FieldEQ(FieldUpdatedAt, v))
}

// NumRow applies equality check predicate on the "num_row" field. It's identical to NumRowEQ.
func NumRow(v int64) predicate.Cinema {
	return predicate.Cinema(sql.FieldEQ(FieldNumRow, v))
}

// NumColumn applies equality check predicate on the "num_column" field. It's identical to NumColumnEQ.
func NumColumn(v int64) predicate.Cinema {
	return predicate.Cinema(sql.FieldEQ(FieldNumColumn, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Cinema {
	return predicate.Cinema(sql.FieldEQ(FieldName, v))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v string) predicate.Cinema {
	return predicate.Cinema(sql.FieldEQ(FieldAddress, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Cinema {
	return predicate.Cinema(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Cinema {
	return predicate.Cinema(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Cinema {
	return predicate.Cinema(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Cinema {
	return predicate.Cinema(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Cinema {
	return predicate.Cinema(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Cinema {
	return predicate.Cinema(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Cinema {
	return predicate.Cinema(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Cinema {
	return predicate.Cinema(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Cinema {
	return predicate.Cinema(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Cinema {
	return predicate.Cinema(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Cinema {
	return predicate.Cinema(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Cinema {
	return predicate.Cinema(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Cinema {
	return predicate.Cinema(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Cinema {
	return predicate.Cinema(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Cinema {
	return predicate.Cinema(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Cinema {
	return predicate.Cinema(sql.FieldLTE(FieldUpdatedAt, v))
}

// NumRowEQ applies the EQ predicate on the "num_row" field.
func NumRowEQ(v int64) predicate.Cinema {
	return predicate.Cinema(sql.FieldEQ(FieldNumRow, v))
}

// NumRowNEQ applies the NEQ predicate on the "num_row" field.
func NumRowNEQ(v int64) predicate.Cinema {
	return predicate.Cinema(sql.FieldNEQ(FieldNumRow, v))
}

// NumRowIn applies the In predicate on the "num_row" field.
func NumRowIn(vs ...int64) predicate.Cinema {
	return predicate.Cinema(sql.FieldIn(FieldNumRow, vs...))
}

// NumRowNotIn applies the NotIn predicate on the "num_row" field.
func NumRowNotIn(vs ...int64) predicate.Cinema {
	return predicate.Cinema(sql.FieldNotIn(FieldNumRow, vs...))
}

// NumRowGT applies the GT predicate on the "num_row" field.
func NumRowGT(v int64) predicate.Cinema {
	return predicate.Cinema(sql.FieldGT(FieldNumRow, v))
}

// NumRowGTE applies the GTE predicate on the "num_row" field.
func NumRowGTE(v int64) predicate.Cinema {
	return predicate.Cinema(sql.FieldGTE(FieldNumRow, v))
}

// NumRowLT applies the LT predicate on the "num_row" field.
func NumRowLT(v int64) predicate.Cinema {
	return predicate.Cinema(sql.FieldLT(FieldNumRow, v))
}

// NumRowLTE applies the LTE predicate on the "num_row" field.
func NumRowLTE(v int64) predicate.Cinema {
	return predicate.Cinema(sql.FieldLTE(FieldNumRow, v))
}

// NumColumnEQ applies the EQ predicate on the "num_column" field.
func NumColumnEQ(v int64) predicate.Cinema {
	return predicate.Cinema(sql.FieldEQ(FieldNumColumn, v))
}

// NumColumnNEQ applies the NEQ predicate on the "num_column" field.
func NumColumnNEQ(v int64) predicate.Cinema {
	return predicate.Cinema(sql.FieldNEQ(FieldNumColumn, v))
}

// NumColumnIn applies the In predicate on the "num_column" field.
func NumColumnIn(vs ...int64) predicate.Cinema {
	return predicate.Cinema(sql.FieldIn(FieldNumColumn, vs...))
}

// NumColumnNotIn applies the NotIn predicate on the "num_column" field.
func NumColumnNotIn(vs ...int64) predicate.Cinema {
	return predicate.Cinema(sql.FieldNotIn(FieldNumColumn, vs...))
}

// NumColumnGT applies the GT predicate on the "num_column" field.
func NumColumnGT(v int64) predicate.Cinema {
	return predicate.Cinema(sql.FieldGT(FieldNumColumn, v))
}

// NumColumnGTE applies the GTE predicate on the "num_column" field.
func NumColumnGTE(v int64) predicate.Cinema {
	return predicate.Cinema(sql.FieldGTE(FieldNumColumn, v))
}

// NumColumnLT applies the LT predicate on the "num_column" field.
func NumColumnLT(v int64) predicate.Cinema {
	return predicate.Cinema(sql.FieldLT(FieldNumColumn, v))
}

// NumColumnLTE applies the LTE predicate on the "num_column" field.
func NumColumnLTE(v int64) predicate.Cinema {
	return predicate.Cinema(sql.FieldLTE(FieldNumColumn, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Cinema {
	return predicate.Cinema(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Cinema {
	return predicate.Cinema(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Cinema {
	return predicate.Cinema(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Cinema {
	return predicate.Cinema(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Cinema {
	return predicate.Cinema(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Cinema {
	return predicate.Cinema(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Cinema {
	return predicate.Cinema(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Cinema {
	return predicate.Cinema(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Cinema {
	return predicate.Cinema(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Cinema {
	return predicate.Cinema(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Cinema {
	return predicate.Cinema(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Cinema {
	return predicate.Cinema(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Cinema {
	return predicate.Cinema(sql.FieldContainsFold(FieldName, v))
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v string) predicate.Cinema {
	return predicate.Cinema(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v string) predicate.Cinema {
	return predicate.Cinema(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...string) predicate.Cinema {
	return predicate.Cinema(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...string) predicate.Cinema {
	return predicate.Cinema(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v string) predicate.Cinema {
	return predicate.Cinema(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v string) predicate.Cinema {
	return predicate.Cinema(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v string) predicate.Cinema {
	return predicate.Cinema(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v string) predicate.Cinema {
	return predicate.Cinema(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v string) predicate.Cinema {
	return predicate.Cinema(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v string) predicate.Cinema {
	return predicate.Cinema(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v string) predicate.Cinema {
	return predicate.Cinema(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v string) predicate.Cinema {
	return predicate.Cinema(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v string) predicate.Cinema {
	return predicate.Cinema(sql.FieldContainsFold(FieldAddress, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Cinema) predicate.Cinema {
	return predicate.Cinema(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Cinema) predicate.Cinema {
	return predicate.Cinema(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Cinema) predicate.Cinema {
	return predicate.Cinema(sql.NotPredicates(p))
}
