// Code generated by ent, DO NOT EDIT.

package ent

import (
	entcinema "cinema/pkg/ent/cinema"
	"cinema/pkg/ent/predicate"
	"cinema/pkg/ent/screening"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CinemaQuery is the builder for querying Cinema entities.
type CinemaQuery struct {
	config
	ctx            *QueryContext
	order          []entcinema.OrderOption
	inters         []Interceptor
	predicates     []predicate.Cinema
	withScreenings *ScreeningQuery
	modifiers      []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CinemaQuery builder.
func (cq *CinemaQuery) Where(ps ...predicate.Cinema) *CinemaQuery {
	cq.predicates = append(cq.predicates, ps...)
	return cq
}

// Limit the number of records to be returned by this query.
func (cq *CinemaQuery) Limit(limit int) *CinemaQuery {
	cq.ctx.Limit = &limit
	return cq
}

// Offset to start from.
func (cq *CinemaQuery) Offset(offset int) *CinemaQuery {
	cq.ctx.Offset = &offset
	return cq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cq *CinemaQuery) Unique(unique bool) *CinemaQuery {
	cq.ctx.Unique = &unique
	return cq
}

// Order specifies how the records should be ordered.
func (cq *CinemaQuery) Order(o ...entcinema.OrderOption) *CinemaQuery {
	cq.order = append(cq.order, o...)
	return cq
}

// QueryScreenings chains the current query on the "screenings" edge.
func (cq *CinemaQuery) QueryScreenings() *ScreeningQuery {
	query := (&ScreeningClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(entcinema.Table, entcinema.FieldID, selector),
			sqlgraph.To(screening.Table, screening.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, entcinema.ScreeningsTable, entcinema.ScreeningsColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Cinema entity from the query.
// Returns a *NotFoundError when no Cinema was found.
func (cq *CinemaQuery) First(ctx context.Context) (*Cinema, error) {
	nodes, err := cq.Limit(1).All(setContextOp(ctx, cq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{entcinema.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cq *CinemaQuery) FirstX(ctx context.Context) *Cinema {
	node, err := cq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Cinema ID from the query.
// Returns a *NotFoundError when no Cinema ID was found.
func (cq *CinemaQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = cq.Limit(1).IDs(setContextOp(ctx, cq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{entcinema.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cq *CinemaQuery) FirstIDX(ctx context.Context) int64 {
	id, err := cq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Cinema entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Cinema entity is found.
// Returns a *NotFoundError when no Cinema entities are found.
func (cq *CinemaQuery) Only(ctx context.Context) (*Cinema, error) {
	nodes, err := cq.Limit(2).All(setContextOp(ctx, cq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{entcinema.Label}
	default:
		return nil, &NotSingularError{entcinema.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cq *CinemaQuery) OnlyX(ctx context.Context) *Cinema {
	node, err := cq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Cinema ID in the query.
// Returns a *NotSingularError when more than one Cinema ID is found.
// Returns a *NotFoundError when no entities are found.
func (cq *CinemaQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = cq.Limit(2).IDs(setContextOp(ctx, cq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{entcinema.Label}
	default:
		err = &NotSingularError{entcinema.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cq *CinemaQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := cq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Cinemas.
func (cq *CinemaQuery) All(ctx context.Context) ([]*Cinema, error) {
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryAll)
	if err := cq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Cinema, *CinemaQuery]()
	return withInterceptors[[]*Cinema](ctx, cq, qr, cq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cq *CinemaQuery) AllX(ctx context.Context) []*Cinema {
	nodes, err := cq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Cinema IDs.
func (cq *CinemaQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if cq.ctx.Unique == nil && cq.path != nil {
		cq.Unique(true)
	}
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryIDs)
	if err = cq.Select(entcinema.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cq *CinemaQuery) IDsX(ctx context.Context) []int64 {
	ids, err := cq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cq *CinemaQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryCount)
	if err := cq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cq, querierCount[*CinemaQuery](), cq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cq *CinemaQuery) CountX(ctx context.Context) int {
	count, err := cq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cq *CinemaQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryExist)
	switch _, err := cq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cq *CinemaQuery) ExistX(ctx context.Context) bool {
	exist, err := cq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CinemaQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cq *CinemaQuery) Clone() *CinemaQuery {
	if cq == nil {
		return nil
	}
	return &CinemaQuery{
		config:         cq.config,
		ctx:            cq.ctx.Clone(),
		order:          append([]entcinema.OrderOption{}, cq.order...),
		inters:         append([]Interceptor{}, cq.inters...),
		predicates:     append([]predicate.Cinema{}, cq.predicates...),
		withScreenings: cq.withScreenings.Clone(),
		// clone intermediate query.
		sql:       cq.sql.Clone(),
		path:      cq.path,
		modifiers: append([]func(*sql.Selector){}, cq.modifiers...),
	}
}

// WithScreenings tells the query-builder to eager-load the nodes that are connected to
// the "screenings" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *CinemaQuery) WithScreenings(opts ...func(*ScreeningQuery)) *CinemaQuery {
	query := (&ScreeningClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withScreenings = query
	return cq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Cinema.Query().
//		GroupBy(entcinema.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cq *CinemaQuery) GroupBy(field string, fields ...string) *CinemaGroupBy {
	cq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CinemaGroupBy{build: cq}
	grbuild.flds = &cq.ctx.Fields
	grbuild.label = entcinema.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Cinema.Query().
//		Select(entcinema.FieldCreatedAt).
//		Scan(ctx, &v)
func (cq *CinemaQuery) Select(fields ...string) *CinemaSelect {
	cq.ctx.Fields = append(cq.ctx.Fields, fields...)
	sbuild := &CinemaSelect{CinemaQuery: cq}
	sbuild.label = entcinema.Label
	sbuild.flds, sbuild.scan = &cq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CinemaSelect configured with the given aggregations.
func (cq *CinemaQuery) Aggregate(fns ...AggregateFunc) *CinemaSelect {
	return cq.Select().Aggregate(fns...)
}

func (cq *CinemaQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cq); err != nil {
				return err
			}
		}
	}
	for _, f := range cq.ctx.Fields {
		if !entcinema.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cq.path != nil {
		prev, err := cq.path(ctx)
		if err != nil {
			return err
		}
		cq.sql = prev
	}
	return nil
}

func (cq *CinemaQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Cinema, error) {
	var (
		nodes       = []*Cinema{}
		_spec       = cq.querySpec()
		loadedTypes = [1]bool{
			cq.withScreenings != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Cinema).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Cinema{config: cq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(cq.modifiers) > 0 {
		_spec.Modifiers = cq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := cq.withScreenings; query != nil {
		if err := cq.loadScreenings(ctx, query, nodes,
			func(n *Cinema) { n.Edges.Screenings = []*Screening{} },
			func(n *Cinema, e *Screening) { n.Edges.Screenings = append(n.Edges.Screenings, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (cq *CinemaQuery) loadScreenings(ctx context.Context, query *ScreeningQuery, nodes []*Cinema, init func(*Cinema), assign func(*Cinema, *Screening)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*Cinema)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Screening(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(entcinema.ScreeningsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.cinema_screenings
		if fk == nil {
			return fmt.Errorf(`foreign-key "cinema_screenings" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "cinema_screenings" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (cq *CinemaQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cq.querySpec()
	if len(cq.modifiers) > 0 {
		_spec.Modifiers = cq.modifiers
	}
	_spec.Node.Columns = cq.ctx.Fields
	if len(cq.ctx.Fields) > 0 {
		_spec.Unique = cq.ctx.Unique != nil && *cq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cq.driver, _spec)
}

func (cq *CinemaQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(entcinema.Table, entcinema.Columns, sqlgraph.NewFieldSpec(entcinema.FieldID, field.TypeInt64))
	_spec.From = cq.sql
	if unique := cq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cq.path != nil {
		_spec.Unique = true
	}
	if fields := cq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entcinema.FieldID)
		for i := range fields {
			if fields[i] != entcinema.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cq *CinemaQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cq.driver.Dialect())
	t1 := builder.Table(entcinema.Table)
	columns := cq.ctx.Fields
	if len(columns) == 0 {
		columns = entcinema.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cq.sql != nil {
		selector = cq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cq.ctx.Unique != nil && *cq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range cq.modifiers {
		m(selector)
	}
	for _, p := range cq.predicates {
		p(selector)
	}
	for _, p := range cq.order {
		p(selector)
	}
	if offset := cq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (cq *CinemaQuery) ForUpdate(opts ...sql.LockOption) *CinemaQuery {
	if cq.driver.Dialect() == dialect.Postgres {
		cq.Unique(false)
	}
	cq.modifiers = append(cq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return cq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (cq *CinemaQuery) ForShare(opts ...sql.LockOption) *CinemaQuery {
	if cq.driver.Dialect() == dialect.Postgres {
		cq.Unique(false)
	}
	cq.modifiers = append(cq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return cq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (cq *CinemaQuery) Modify(modifiers ...func(s *sql.Selector)) *CinemaSelect {
	cq.modifiers = append(cq.modifiers, modifiers...)
	return cq.Select()
}

// CinemaGroupBy is the group-by builder for Cinema entities.
type CinemaGroupBy struct {
	selector
	build *CinemaQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cgb *CinemaGroupBy) Aggregate(fns ...AggregateFunc) *CinemaGroupBy {
	cgb.fns = append(cgb.fns, fns...)
	return cgb
}

// Scan applies the selector query and scans the result into the given value.
func (cgb *CinemaGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cgb.build.ctx, ent.OpQueryGroupBy)
	if err := cgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CinemaQuery, *CinemaGroupBy](ctx, cgb.build, cgb, cgb.build.inters, v)
}

func (cgb *CinemaGroupBy) sqlScan(ctx context.Context, root *CinemaQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cgb.fns))
	for _, fn := range cgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cgb.flds)+len(cgb.fns))
		for _, f := range *cgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CinemaSelect is the builder for selecting fields of Cinema entities.
type CinemaSelect struct {
	*CinemaQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cs *CinemaSelect) Aggregate(fns ...AggregateFunc) *CinemaSelect {
	cs.fns = append(cs.fns, fns...)
	return cs
}

// Scan applies the selector query and scans the result into the given value.
func (cs *CinemaSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cs.ctx, ent.OpQuerySelect)
	if err := cs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CinemaQuery, *CinemaSelect](ctx, cs.CinemaQuery, cs, cs.inters, v)
}

func (cs *CinemaSelect) sqlScan(ctx context.Context, root *CinemaQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cs.fns))
	for _, fn := range cs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (cs *CinemaSelect) Modify(modifiers ...func(s *sql.Selector)) *CinemaSelect {
	cs.modifiers = append(cs.modifiers, modifiers...)
	return cs
}
