// Code generated by ent, DO NOT EDIT.

package ent

import (
	cinema "cinema/api"
	entcinema "cinema/pkg/ent/cinema"
	"cinema/pkg/ent/movie"
	"cinema/pkg/ent/predicate"
	"cinema/pkg/ent/screening"
	"cinema/pkg/ent/seatreservation"
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeCinema          = "Cinema"
	TypeMovie           = "Movie"
	TypeScreening       = "Screening"
	TypeSeatReservation = "SeatReservation"
)

// CinemaMutation represents an operation that mutates the Cinema nodes in the graph.
type CinemaMutation struct {
	config
	op                Op
	typ               string
	id                *int64
	created_at        *time.Time
	updated_at        *time.Time
	num_row           *uint32
	addnum_row        *int32
	num_column        *uint32
	addnum_column     *int32
	name              *string
	min_distance      *uint32
	addmin_distance   *int32
	clearedFields     map[string]struct{}
	screenings        map[int64]struct{}
	removedscreenings map[int64]struct{}
	clearedscreenings bool
	done              bool
	oldValue          func(context.Context) (*Cinema, error)
	predicates        []predicate.Cinema
}

var _ ent.Mutation = (*CinemaMutation)(nil)

// cinemaOption allows management of the mutation configuration using functional options.
type cinemaOption func(*CinemaMutation)

// newCinemaMutation creates new mutation for the Cinema entity.
func newCinemaMutation(c config, op Op, opts ...cinemaOption) *CinemaMutation {
	m := &CinemaMutation{
		config:        c,
		op:            op,
		typ:           TypeCinema,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withCinemaID sets the ID field of the mutation.
func withCinemaID(id int64) cinemaOption {
	return func(m *CinemaMutation) {
		var (
			err   error
			once  sync.Once
			value *Cinema
		)
		m.oldValue = func(ctx context.Context) (*Cinema, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Cinema.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withCinema sets the old Cinema of the mutation.
func withCinema(node *Cinema) cinemaOption {
	return func(m *CinemaMutation) {
		m.oldValue = func(context.Context) (*Cinema, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m CinemaMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m CinemaMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Cinema entities.
func (m *CinemaMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *CinemaMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *CinemaMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Cinema.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *CinemaMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *CinemaMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Cinema entity.
// If the Cinema object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CinemaMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *CinemaMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *CinemaMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *CinemaMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Cinema entity.
// If the Cinema object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CinemaMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *CinemaMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetNumRow sets the "num_row" field.
func (m *CinemaMutation) SetNumRow(u uint32) {
	m.num_row = &u
	m.addnum_row = nil
}

// NumRow returns the value of the "num_row" field in the mutation.
func (m *CinemaMutation) NumRow() (r uint32, exists bool) {
	v := m.num_row
	if v == nil {
		return
	}
	return *v, true
}

// OldNumRow returns the old "num_row" field's value of the Cinema entity.
// If the Cinema object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CinemaMutation) OldNumRow(ctx context.Context) (v uint32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNumRow is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNumRow requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNumRow: %w", err)
	}
	return oldValue.NumRow, nil
}

// AddNumRow adds u to the "num_row" field.
func (m *CinemaMutation) AddNumRow(u int32) {
	if m.addnum_row != nil {
		*m.addnum_row += u
	} else {
		m.addnum_row = &u
	}
}

// AddedNumRow returns the value that was added to the "num_row" field in this mutation.
func (m *CinemaMutation) AddedNumRow() (r int32, exists bool) {
	v := m.addnum_row
	if v == nil {
		return
	}
	return *v, true
}

// ResetNumRow resets all changes to the "num_row" field.
func (m *CinemaMutation) ResetNumRow() {
	m.num_row = nil
	m.addnum_row = nil
}

// SetNumColumn sets the "num_column" field.
func (m *CinemaMutation) SetNumColumn(u uint32) {
	m.num_column = &u
	m.addnum_column = nil
}

// NumColumn returns the value of the "num_column" field in the mutation.
func (m *CinemaMutation) NumColumn() (r uint32, exists bool) {
	v := m.num_column
	if v == nil {
		return
	}
	return *v, true
}

// OldNumColumn returns the old "num_column" field's value of the Cinema entity.
// If the Cinema object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CinemaMutation) OldNumColumn(ctx context.Context) (v uint32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNumColumn is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNumColumn requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNumColumn: %w", err)
	}
	return oldValue.NumColumn, nil
}

// AddNumColumn adds u to the "num_column" field.
func (m *CinemaMutation) AddNumColumn(u int32) {
	if m.addnum_column != nil {
		*m.addnum_column += u
	} else {
		m.addnum_column = &u
	}
}

// AddedNumColumn returns the value that was added to the "num_column" field in this mutation.
func (m *CinemaMutation) AddedNumColumn() (r int32, exists bool) {
	v := m.addnum_column
	if v == nil {
		return
	}
	return *v, true
}

// ResetNumColumn resets all changes to the "num_column" field.
func (m *CinemaMutation) ResetNumColumn() {
	m.num_column = nil
	m.addnum_column = nil
}

// SetName sets the "name" field.
func (m *CinemaMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *CinemaMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Cinema entity.
// If the Cinema object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CinemaMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *CinemaMutation) ResetName() {
	m.name = nil
}

// SetMinDistance sets the "min_distance" field.
func (m *CinemaMutation) SetMinDistance(u uint32) {
	m.min_distance = &u
	m.addmin_distance = nil
}

// MinDistance returns the value of the "min_distance" field in the mutation.
func (m *CinemaMutation) MinDistance() (r uint32, exists bool) {
	v := m.min_distance
	if v == nil {
		return
	}
	return *v, true
}

// OldMinDistance returns the old "min_distance" field's value of the Cinema entity.
// If the Cinema object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CinemaMutation) OldMinDistance(ctx context.Context) (v uint32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMinDistance is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMinDistance requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMinDistance: %w", err)
	}
	return oldValue.MinDistance, nil
}

// AddMinDistance adds u to the "min_distance" field.
func (m *CinemaMutation) AddMinDistance(u int32) {
	if m.addmin_distance != nil {
		*m.addmin_distance += u
	} else {
		m.addmin_distance = &u
	}
}

// AddedMinDistance returns the value that was added to the "min_distance" field in this mutation.
func (m *CinemaMutation) AddedMinDistance() (r int32, exists bool) {
	v := m.addmin_distance
	if v == nil {
		return
	}
	return *v, true
}

// ResetMinDistance resets all changes to the "min_distance" field.
func (m *CinemaMutation) ResetMinDistance() {
	m.min_distance = nil
	m.addmin_distance = nil
}

// AddScreeningIDs adds the "screenings" edge to the Screening entity by ids.
func (m *CinemaMutation) AddScreeningIDs(ids ...int64) {
	if m.screenings == nil {
		m.screenings = make(map[int64]struct{})
	}
	for i := range ids {
		m.screenings[ids[i]] = struct{}{}
	}
}

// ClearScreenings clears the "screenings" edge to the Screening entity.
func (m *CinemaMutation) ClearScreenings() {
	m.clearedscreenings = true
}

// ScreeningsCleared reports if the "screenings" edge to the Screening entity was cleared.
func (m *CinemaMutation) ScreeningsCleared() bool {
	return m.clearedscreenings
}

// RemoveScreeningIDs removes the "screenings" edge to the Screening entity by IDs.
func (m *CinemaMutation) RemoveScreeningIDs(ids ...int64) {
	if m.removedscreenings == nil {
		m.removedscreenings = make(map[int64]struct{})
	}
	for i := range ids {
		delete(m.screenings, ids[i])
		m.removedscreenings[ids[i]] = struct{}{}
	}
}

// RemovedScreenings returns the removed IDs of the "screenings" edge to the Screening entity.
func (m *CinemaMutation) RemovedScreeningsIDs() (ids []int64) {
	for id := range m.removedscreenings {
		ids = append(ids, id)
	}
	return
}

// ScreeningsIDs returns the "screenings" edge IDs in the mutation.
func (m *CinemaMutation) ScreeningsIDs() (ids []int64) {
	for id := range m.screenings {
		ids = append(ids, id)
	}
	return
}

// ResetScreenings resets all changes to the "screenings" edge.
func (m *CinemaMutation) ResetScreenings() {
	m.screenings = nil
	m.clearedscreenings = false
	m.removedscreenings = nil
}

// Where appends a list predicates to the CinemaMutation builder.
func (m *CinemaMutation) Where(ps ...predicate.Cinema) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the CinemaMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *CinemaMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Cinema, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *CinemaMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *CinemaMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Cinema).
func (m *CinemaMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *CinemaMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.created_at != nil {
		fields = append(fields, entcinema.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, entcinema.FieldUpdatedAt)
	}
	if m.num_row != nil {
		fields = append(fields, entcinema.FieldNumRow)
	}
	if m.num_column != nil {
		fields = append(fields, entcinema.FieldNumColumn)
	}
	if m.name != nil {
		fields = append(fields, entcinema.FieldName)
	}
	if m.min_distance != nil {
		fields = append(fields, entcinema.FieldMinDistance)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *CinemaMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case entcinema.FieldCreatedAt:
		return m.CreatedAt()
	case entcinema.FieldUpdatedAt:
		return m.UpdatedAt()
	case entcinema.FieldNumRow:
		return m.NumRow()
	case entcinema.FieldNumColumn:
		return m.NumColumn()
	case entcinema.FieldName:
		return m.Name()
	case entcinema.FieldMinDistance:
		return m.MinDistance()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *CinemaMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case entcinema.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case entcinema.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case entcinema.FieldNumRow:
		return m.OldNumRow(ctx)
	case entcinema.FieldNumColumn:
		return m.OldNumColumn(ctx)
	case entcinema.FieldName:
		return m.OldName(ctx)
	case entcinema.FieldMinDistance:
		return m.OldMinDistance(ctx)
	}
	return nil, fmt.Errorf("unknown Cinema field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *CinemaMutation) SetField(name string, value ent.Value) error {
	switch name {
	case entcinema.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case entcinema.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case entcinema.FieldNumRow:
		v, ok := value.(uint32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNumRow(v)
		return nil
	case entcinema.FieldNumColumn:
		v, ok := value.(uint32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNumColumn(v)
		return nil
	case entcinema.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case entcinema.FieldMinDistance:
		v, ok := value.(uint32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMinDistance(v)
		return nil
	}
	return fmt.Errorf("unknown Cinema field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *CinemaMutation) AddedFields() []string {
	var fields []string
	if m.addnum_row != nil {
		fields = append(fields, entcinema.FieldNumRow)
	}
	if m.addnum_column != nil {
		fields = append(fields, entcinema.FieldNumColumn)
	}
	if m.addmin_distance != nil {
		fields = append(fields, entcinema.FieldMinDistance)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *CinemaMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case entcinema.FieldNumRow:
		return m.AddedNumRow()
	case entcinema.FieldNumColumn:
		return m.AddedNumColumn()
	case entcinema.FieldMinDistance:
		return m.AddedMinDistance()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *CinemaMutation) AddField(name string, value ent.Value) error {
	switch name {
	case entcinema.FieldNumRow:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddNumRow(v)
		return nil
	case entcinema.FieldNumColumn:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddNumColumn(v)
		return nil
	case entcinema.FieldMinDistance:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddMinDistance(v)
		return nil
	}
	return fmt.Errorf("unknown Cinema numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *CinemaMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *CinemaMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *CinemaMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Cinema nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *CinemaMutation) ResetField(name string) error {
	switch name {
	case entcinema.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case entcinema.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case entcinema.FieldNumRow:
		m.ResetNumRow()
		return nil
	case entcinema.FieldNumColumn:
		m.ResetNumColumn()
		return nil
	case entcinema.FieldName:
		m.ResetName()
		return nil
	case entcinema.FieldMinDistance:
		m.ResetMinDistance()
		return nil
	}
	return fmt.Errorf("unknown Cinema field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *CinemaMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.screenings != nil {
		edges = append(edges, entcinema.EdgeScreenings)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *CinemaMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case entcinema.EdgeScreenings:
		ids := make([]ent.Value, 0, len(m.screenings))
		for id := range m.screenings {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *CinemaMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedscreenings != nil {
		edges = append(edges, entcinema.EdgeScreenings)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *CinemaMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case entcinema.EdgeScreenings:
		ids := make([]ent.Value, 0, len(m.removedscreenings))
		for id := range m.removedscreenings {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *CinemaMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedscreenings {
		edges = append(edges, entcinema.EdgeScreenings)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *CinemaMutation) EdgeCleared(name string) bool {
	switch name {
	case entcinema.EdgeScreenings:
		return m.clearedscreenings
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *CinemaMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Cinema unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *CinemaMutation) ResetEdge(name string) error {
	switch name {
	case entcinema.EdgeScreenings:
		m.ResetScreenings()
		return nil
	}
	return fmt.Errorf("unknown Cinema edge %s", name)
}

// MovieMutation represents an operation that mutates the Movie nodes in the graph.
type MovieMutation struct {
	config
	op                Op
	typ               string
	id                *int64
	created_at        *time.Time
	updated_at        *time.Time
	title             *string
	duration          *uint64
	addduration       *int64
	clearedFields     map[string]struct{}
	screenings        map[int64]struct{}
	removedscreenings map[int64]struct{}
	clearedscreenings bool
	done              bool
	oldValue          func(context.Context) (*Movie, error)
	predicates        []predicate.Movie
}

var _ ent.Mutation = (*MovieMutation)(nil)

// movieOption allows management of the mutation configuration using functional options.
type movieOption func(*MovieMutation)

// newMovieMutation creates new mutation for the Movie entity.
func newMovieMutation(c config, op Op, opts ...movieOption) *MovieMutation {
	m := &MovieMutation{
		config:        c,
		op:            op,
		typ:           TypeMovie,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withMovieID sets the ID field of the mutation.
func withMovieID(id int64) movieOption {
	return func(m *MovieMutation) {
		var (
			err   error
			once  sync.Once
			value *Movie
		)
		m.oldValue = func(ctx context.Context) (*Movie, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Movie.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withMovie sets the old Movie of the mutation.
func withMovie(node *Movie) movieOption {
	return func(m *MovieMutation) {
		m.oldValue = func(context.Context) (*Movie, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m MovieMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m MovieMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Movie entities.
func (m *MovieMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *MovieMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *MovieMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Movie.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *MovieMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *MovieMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Movie entity.
// If the Movie object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MovieMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *MovieMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *MovieMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *MovieMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Movie entity.
// If the Movie object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MovieMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *MovieMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetTitle sets the "title" field.
func (m *MovieMutation) SetTitle(s string) {
	m.title = &s
}

// Title returns the value of the "title" field in the mutation.
func (m *MovieMutation) Title() (r string, exists bool) {
	v := m.title
	if v == nil {
		return
	}
	return *v, true
}

// OldTitle returns the old "title" field's value of the Movie entity.
// If the Movie object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MovieMutation) OldTitle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTitle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTitle: %w", err)
	}
	return oldValue.Title, nil
}

// ResetTitle resets all changes to the "title" field.
func (m *MovieMutation) ResetTitle() {
	m.title = nil
}

// SetDuration sets the "duration" field.
func (m *MovieMutation) SetDuration(u uint64) {
	m.duration = &u
	m.addduration = nil
}

// Duration returns the value of the "duration" field in the mutation.
func (m *MovieMutation) Duration() (r uint64, exists bool) {
	v := m.duration
	if v == nil {
		return
	}
	return *v, true
}

// OldDuration returns the old "duration" field's value of the Movie entity.
// If the Movie object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MovieMutation) OldDuration(ctx context.Context) (v uint64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDuration is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDuration requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDuration: %w", err)
	}
	return oldValue.Duration, nil
}

// AddDuration adds u to the "duration" field.
func (m *MovieMutation) AddDuration(u int64) {
	if m.addduration != nil {
		*m.addduration += u
	} else {
		m.addduration = &u
	}
}

// AddedDuration returns the value that was added to the "duration" field in this mutation.
func (m *MovieMutation) AddedDuration() (r int64, exists bool) {
	v := m.addduration
	if v == nil {
		return
	}
	return *v, true
}

// ResetDuration resets all changes to the "duration" field.
func (m *MovieMutation) ResetDuration() {
	m.duration = nil
	m.addduration = nil
}

// AddScreeningIDs adds the "screenings" edge to the Screening entity by ids.
func (m *MovieMutation) AddScreeningIDs(ids ...int64) {
	if m.screenings == nil {
		m.screenings = make(map[int64]struct{})
	}
	for i := range ids {
		m.screenings[ids[i]] = struct{}{}
	}
}

// ClearScreenings clears the "screenings" edge to the Screening entity.
func (m *MovieMutation) ClearScreenings() {
	m.clearedscreenings = true
}

// ScreeningsCleared reports if the "screenings" edge to the Screening entity was cleared.
func (m *MovieMutation) ScreeningsCleared() bool {
	return m.clearedscreenings
}

// RemoveScreeningIDs removes the "screenings" edge to the Screening entity by IDs.
func (m *MovieMutation) RemoveScreeningIDs(ids ...int64) {
	if m.removedscreenings == nil {
		m.removedscreenings = make(map[int64]struct{})
	}
	for i := range ids {
		delete(m.screenings, ids[i])
		m.removedscreenings[ids[i]] = struct{}{}
	}
}

// RemovedScreenings returns the removed IDs of the "screenings" edge to the Screening entity.
func (m *MovieMutation) RemovedScreeningsIDs() (ids []int64) {
	for id := range m.removedscreenings {
		ids = append(ids, id)
	}
	return
}

// ScreeningsIDs returns the "screenings" edge IDs in the mutation.
func (m *MovieMutation) ScreeningsIDs() (ids []int64) {
	for id := range m.screenings {
		ids = append(ids, id)
	}
	return
}

// ResetScreenings resets all changes to the "screenings" edge.
func (m *MovieMutation) ResetScreenings() {
	m.screenings = nil
	m.clearedscreenings = false
	m.removedscreenings = nil
}

// Where appends a list predicates to the MovieMutation builder.
func (m *MovieMutation) Where(ps ...predicate.Movie) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the MovieMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *MovieMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Movie, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *MovieMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *MovieMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Movie).
func (m *MovieMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *MovieMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.created_at != nil {
		fields = append(fields, movie.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, movie.FieldUpdatedAt)
	}
	if m.title != nil {
		fields = append(fields, movie.FieldTitle)
	}
	if m.duration != nil {
		fields = append(fields, movie.FieldDuration)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *MovieMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case movie.FieldCreatedAt:
		return m.CreatedAt()
	case movie.FieldUpdatedAt:
		return m.UpdatedAt()
	case movie.FieldTitle:
		return m.Title()
	case movie.FieldDuration:
		return m.Duration()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *MovieMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case movie.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case movie.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case movie.FieldTitle:
		return m.OldTitle(ctx)
	case movie.FieldDuration:
		return m.OldDuration(ctx)
	}
	return nil, fmt.Errorf("unknown Movie field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *MovieMutation) SetField(name string, value ent.Value) error {
	switch name {
	case movie.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case movie.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case movie.FieldTitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTitle(v)
		return nil
	case movie.FieldDuration:
		v, ok := value.(uint64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDuration(v)
		return nil
	}
	return fmt.Errorf("unknown Movie field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *MovieMutation) AddedFields() []string {
	var fields []string
	if m.addduration != nil {
		fields = append(fields, movie.FieldDuration)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *MovieMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case movie.FieldDuration:
		return m.AddedDuration()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *MovieMutation) AddField(name string, value ent.Value) error {
	switch name {
	case movie.FieldDuration:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddDuration(v)
		return nil
	}
	return fmt.Errorf("unknown Movie numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *MovieMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *MovieMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *MovieMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Movie nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *MovieMutation) ResetField(name string) error {
	switch name {
	case movie.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case movie.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case movie.FieldTitle:
		m.ResetTitle()
		return nil
	case movie.FieldDuration:
		m.ResetDuration()
		return nil
	}
	return fmt.Errorf("unknown Movie field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *MovieMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.screenings != nil {
		edges = append(edges, movie.EdgeScreenings)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *MovieMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case movie.EdgeScreenings:
		ids := make([]ent.Value, 0, len(m.screenings))
		for id := range m.screenings {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *MovieMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedscreenings != nil {
		edges = append(edges, movie.EdgeScreenings)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *MovieMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case movie.EdgeScreenings:
		ids := make([]ent.Value, 0, len(m.removedscreenings))
		for id := range m.removedscreenings {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *MovieMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedscreenings {
		edges = append(edges, movie.EdgeScreenings)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *MovieMutation) EdgeCleared(name string) bool {
	switch name {
	case movie.EdgeScreenings:
		return m.clearedscreenings
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *MovieMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Movie unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *MovieMutation) ResetEdge(name string) error {
	switch name {
	case movie.EdgeScreenings:
		m.ResetScreenings()
		return nil
	}
	return fmt.Errorf("unknown Movie edge %s", name)
}

// ScreeningMutation represents an operation that mutates the Screening nodes in the graph.
type ScreeningMutation struct {
	config
	op                       Op
	typ                      string
	id                       *int64
	created_at               *time.Time
	updated_at               *time.Time
	title                    *string
	start_time               *time.Time
	clearedFields            map[string]struct{}
	movie                    *int64
	clearedmovie             bool
	cinema                   *int64
	clearedcinema            bool
	seat_reservations        map[int64]struct{}
	removedseat_reservations map[int64]struct{}
	clearedseat_reservations bool
	done                     bool
	oldValue                 func(context.Context) (*Screening, error)
	predicates               []predicate.Screening
}

var _ ent.Mutation = (*ScreeningMutation)(nil)

// screeningOption allows management of the mutation configuration using functional options.
type screeningOption func(*ScreeningMutation)

// newScreeningMutation creates new mutation for the Screening entity.
func newScreeningMutation(c config, op Op, opts ...screeningOption) *ScreeningMutation {
	m := &ScreeningMutation{
		config:        c,
		op:            op,
		typ:           TypeScreening,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withScreeningID sets the ID field of the mutation.
func withScreeningID(id int64) screeningOption {
	return func(m *ScreeningMutation) {
		var (
			err   error
			once  sync.Once
			value *Screening
		)
		m.oldValue = func(ctx context.Context) (*Screening, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Screening.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withScreening sets the old Screening of the mutation.
func withScreening(node *Screening) screeningOption {
	return func(m *ScreeningMutation) {
		m.oldValue = func(context.Context) (*Screening, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ScreeningMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ScreeningMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Screening entities.
func (m *ScreeningMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ScreeningMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ScreeningMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Screening.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *ScreeningMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *ScreeningMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Screening entity.
// If the Screening object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ScreeningMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *ScreeningMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *ScreeningMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *ScreeningMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Screening entity.
// If the Screening object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ScreeningMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *ScreeningMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetTitle sets the "title" field.
func (m *ScreeningMutation) SetTitle(s string) {
	m.title = &s
}

// Title returns the value of the "title" field in the mutation.
func (m *ScreeningMutation) Title() (r string, exists bool) {
	v := m.title
	if v == nil {
		return
	}
	return *v, true
}

// OldTitle returns the old "title" field's value of the Screening entity.
// If the Screening object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ScreeningMutation) OldTitle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTitle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTitle: %w", err)
	}
	return oldValue.Title, nil
}

// ResetTitle resets all changes to the "title" field.
func (m *ScreeningMutation) ResetTitle() {
	m.title = nil
}

// SetStartTime sets the "start_time" field.
func (m *ScreeningMutation) SetStartTime(t time.Time) {
	m.start_time = &t
}

// StartTime returns the value of the "start_time" field in the mutation.
func (m *ScreeningMutation) StartTime() (r time.Time, exists bool) {
	v := m.start_time
	if v == nil {
		return
	}
	return *v, true
}

// OldStartTime returns the old "start_time" field's value of the Screening entity.
// If the Screening object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ScreeningMutation) OldStartTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStartTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStartTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStartTime: %w", err)
	}
	return oldValue.StartTime, nil
}

// ResetStartTime resets all changes to the "start_time" field.
func (m *ScreeningMutation) ResetStartTime() {
	m.start_time = nil
}

// SetMovieID sets the "movie" edge to the Movie entity by id.
func (m *ScreeningMutation) SetMovieID(id int64) {
	m.movie = &id
}

// ClearMovie clears the "movie" edge to the Movie entity.
func (m *ScreeningMutation) ClearMovie() {
	m.clearedmovie = true
}

// MovieCleared reports if the "movie" edge to the Movie entity was cleared.
func (m *ScreeningMutation) MovieCleared() bool {
	return m.clearedmovie
}

// MovieID returns the "movie" edge ID in the mutation.
func (m *ScreeningMutation) MovieID() (id int64, exists bool) {
	if m.movie != nil {
		return *m.movie, true
	}
	return
}

// MovieIDs returns the "movie" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// MovieID instead. It exists only for internal usage by the builders.
func (m *ScreeningMutation) MovieIDs() (ids []int64) {
	if id := m.movie; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetMovie resets all changes to the "movie" edge.
func (m *ScreeningMutation) ResetMovie() {
	m.movie = nil
	m.clearedmovie = false
}

// SetCinemaID sets the "cinema" edge to the Cinema entity by id.
func (m *ScreeningMutation) SetCinemaID(id int64) {
	m.cinema = &id
}

// ClearCinema clears the "cinema" edge to the Cinema entity.
func (m *ScreeningMutation) ClearCinema() {
	m.clearedcinema = true
}

// CinemaCleared reports if the "cinema" edge to the Cinema entity was cleared.
func (m *ScreeningMutation) CinemaCleared() bool {
	return m.clearedcinema
}

// CinemaID returns the "cinema" edge ID in the mutation.
func (m *ScreeningMutation) CinemaID() (id int64, exists bool) {
	if m.cinema != nil {
		return *m.cinema, true
	}
	return
}

// CinemaIDs returns the "cinema" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// CinemaID instead. It exists only for internal usage by the builders.
func (m *ScreeningMutation) CinemaIDs() (ids []int64) {
	if id := m.cinema; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetCinema resets all changes to the "cinema" edge.
func (m *ScreeningMutation) ResetCinema() {
	m.cinema = nil
	m.clearedcinema = false
}

// AddSeatReservationIDs adds the "seat_reservations" edge to the SeatReservation entity by ids.
func (m *ScreeningMutation) AddSeatReservationIDs(ids ...int64) {
	if m.seat_reservations == nil {
		m.seat_reservations = make(map[int64]struct{})
	}
	for i := range ids {
		m.seat_reservations[ids[i]] = struct{}{}
	}
}

// ClearSeatReservations clears the "seat_reservations" edge to the SeatReservation entity.
func (m *ScreeningMutation) ClearSeatReservations() {
	m.clearedseat_reservations = true
}

// SeatReservationsCleared reports if the "seat_reservations" edge to the SeatReservation entity was cleared.
func (m *ScreeningMutation) SeatReservationsCleared() bool {
	return m.clearedseat_reservations
}

// RemoveSeatReservationIDs removes the "seat_reservations" edge to the SeatReservation entity by IDs.
func (m *ScreeningMutation) RemoveSeatReservationIDs(ids ...int64) {
	if m.removedseat_reservations == nil {
		m.removedseat_reservations = make(map[int64]struct{})
	}
	for i := range ids {
		delete(m.seat_reservations, ids[i])
		m.removedseat_reservations[ids[i]] = struct{}{}
	}
}

// RemovedSeatReservations returns the removed IDs of the "seat_reservations" edge to the SeatReservation entity.
func (m *ScreeningMutation) RemovedSeatReservationsIDs() (ids []int64) {
	for id := range m.removedseat_reservations {
		ids = append(ids, id)
	}
	return
}

// SeatReservationsIDs returns the "seat_reservations" edge IDs in the mutation.
func (m *ScreeningMutation) SeatReservationsIDs() (ids []int64) {
	for id := range m.seat_reservations {
		ids = append(ids, id)
	}
	return
}

// ResetSeatReservations resets all changes to the "seat_reservations" edge.
func (m *ScreeningMutation) ResetSeatReservations() {
	m.seat_reservations = nil
	m.clearedseat_reservations = false
	m.removedseat_reservations = nil
}

// Where appends a list predicates to the ScreeningMutation builder.
func (m *ScreeningMutation) Where(ps ...predicate.Screening) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ScreeningMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ScreeningMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Screening, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ScreeningMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ScreeningMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Screening).
func (m *ScreeningMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ScreeningMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.created_at != nil {
		fields = append(fields, screening.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, screening.FieldUpdatedAt)
	}
	if m.title != nil {
		fields = append(fields, screening.FieldTitle)
	}
	if m.start_time != nil {
		fields = append(fields, screening.FieldStartTime)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ScreeningMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case screening.FieldCreatedAt:
		return m.CreatedAt()
	case screening.FieldUpdatedAt:
		return m.UpdatedAt()
	case screening.FieldTitle:
		return m.Title()
	case screening.FieldStartTime:
		return m.StartTime()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ScreeningMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case screening.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case screening.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case screening.FieldTitle:
		return m.OldTitle(ctx)
	case screening.FieldStartTime:
		return m.OldStartTime(ctx)
	}
	return nil, fmt.Errorf("unknown Screening field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ScreeningMutation) SetField(name string, value ent.Value) error {
	switch name {
	case screening.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case screening.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case screening.FieldTitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTitle(v)
		return nil
	case screening.FieldStartTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStartTime(v)
		return nil
	}
	return fmt.Errorf("unknown Screening field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ScreeningMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ScreeningMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ScreeningMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Screening numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ScreeningMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ScreeningMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ScreeningMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Screening nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ScreeningMutation) ResetField(name string) error {
	switch name {
	case screening.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case screening.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case screening.FieldTitle:
		m.ResetTitle()
		return nil
	case screening.FieldStartTime:
		m.ResetStartTime()
		return nil
	}
	return fmt.Errorf("unknown Screening field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ScreeningMutation) AddedEdges() []string {
	edges := make([]string, 0, 3)
	if m.movie != nil {
		edges = append(edges, screening.EdgeMovie)
	}
	if m.cinema != nil {
		edges = append(edges, screening.EdgeCinema)
	}
	if m.seat_reservations != nil {
		edges = append(edges, screening.EdgeSeatReservations)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ScreeningMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case screening.EdgeMovie:
		if id := m.movie; id != nil {
			return []ent.Value{*id}
		}
	case screening.EdgeCinema:
		if id := m.cinema; id != nil {
			return []ent.Value{*id}
		}
	case screening.EdgeSeatReservations:
		ids := make([]ent.Value, 0, len(m.seat_reservations))
		for id := range m.seat_reservations {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ScreeningMutation) RemovedEdges() []string {
	edges := make([]string, 0, 3)
	if m.removedseat_reservations != nil {
		edges = append(edges, screening.EdgeSeatReservations)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ScreeningMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case screening.EdgeSeatReservations:
		ids := make([]ent.Value, 0, len(m.removedseat_reservations))
		for id := range m.removedseat_reservations {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ScreeningMutation) ClearedEdges() []string {
	edges := make([]string, 0, 3)
	if m.clearedmovie {
		edges = append(edges, screening.EdgeMovie)
	}
	if m.clearedcinema {
		edges = append(edges, screening.EdgeCinema)
	}
	if m.clearedseat_reservations {
		edges = append(edges, screening.EdgeSeatReservations)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ScreeningMutation) EdgeCleared(name string) bool {
	switch name {
	case screening.EdgeMovie:
		return m.clearedmovie
	case screening.EdgeCinema:
		return m.clearedcinema
	case screening.EdgeSeatReservations:
		return m.clearedseat_reservations
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ScreeningMutation) ClearEdge(name string) error {
	switch name {
	case screening.EdgeMovie:
		m.ClearMovie()
		return nil
	case screening.EdgeCinema:
		m.ClearCinema()
		return nil
	}
	return fmt.Errorf("unknown Screening unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ScreeningMutation) ResetEdge(name string) error {
	switch name {
	case screening.EdgeMovie:
		m.ResetMovie()
		return nil
	case screening.EdgeCinema:
		m.ResetCinema()
		return nil
	case screening.EdgeSeatReservations:
		m.ResetSeatReservations()
		return nil
	}
	return fmt.Errorf("unknown Screening edge %s", name)
}

// SeatReservationMutation represents an operation that mutates the SeatReservation nodes in the graph.
type SeatReservationMutation struct {
	config
	op               Op
	typ              string
	id               *int64
	created_at       *time.Time
	updated_at       *time.Time
	reserved_at      *time.Time
	group_id         *uuid.UUID
	status           *cinema.SeatReservationStatus
	addstatus        *cinema.SeatReservationStatus
	row_num          *uint32
	addrow_num       *int32
	column_num       *uint32
	addcolumn_num    *int32
	clearedFields    map[string]struct{}
	screening        *int64
	clearedscreening bool
	done             bool
	oldValue         func(context.Context) (*SeatReservation, error)
	predicates       []predicate.SeatReservation
}

var _ ent.Mutation = (*SeatReservationMutation)(nil)

// seatreservationOption allows management of the mutation configuration using functional options.
type seatreservationOption func(*SeatReservationMutation)

// newSeatReservationMutation creates new mutation for the SeatReservation entity.
func newSeatReservationMutation(c config, op Op, opts ...seatreservationOption) *SeatReservationMutation {
	m := &SeatReservationMutation{
		config:        c,
		op:            op,
		typ:           TypeSeatReservation,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withSeatReservationID sets the ID field of the mutation.
func withSeatReservationID(id int64) seatreservationOption {
	return func(m *SeatReservationMutation) {
		var (
			err   error
			once  sync.Once
			value *SeatReservation
		)
		m.oldValue = func(ctx context.Context) (*SeatReservation, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().SeatReservation.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withSeatReservation sets the old SeatReservation of the mutation.
func withSeatReservation(node *SeatReservation) seatreservationOption {
	return func(m *SeatReservationMutation) {
		m.oldValue = func(context.Context) (*SeatReservation, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m SeatReservationMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m SeatReservationMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of SeatReservation entities.
func (m *SeatReservationMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *SeatReservationMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *SeatReservationMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().SeatReservation.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *SeatReservationMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *SeatReservationMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the SeatReservation entity.
// If the SeatReservation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SeatReservationMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *SeatReservationMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *SeatReservationMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *SeatReservationMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the SeatReservation entity.
// If the SeatReservation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SeatReservationMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *SeatReservationMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetReservedAt sets the "reserved_at" field.
func (m *SeatReservationMutation) SetReservedAt(t time.Time) {
	m.reserved_at = &t
}

// ReservedAt returns the value of the "reserved_at" field in the mutation.
func (m *SeatReservationMutation) ReservedAt() (r time.Time, exists bool) {
	v := m.reserved_at
	if v == nil {
		return
	}
	return *v, true
}

// OldReservedAt returns the old "reserved_at" field's value of the SeatReservation entity.
// If the SeatReservation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SeatReservationMutation) OldReservedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldReservedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldReservedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldReservedAt: %w", err)
	}
	return oldValue.ReservedAt, nil
}

// ResetReservedAt resets all changes to the "reserved_at" field.
func (m *SeatReservationMutation) ResetReservedAt() {
	m.reserved_at = nil
}

// SetGroupID sets the "group_id" field.
func (m *SeatReservationMutation) SetGroupID(u uuid.UUID) {
	m.group_id = &u
}

// GroupID returns the value of the "group_id" field in the mutation.
func (m *SeatReservationMutation) GroupID() (r uuid.UUID, exists bool) {
	v := m.group_id
	if v == nil {
		return
	}
	return *v, true
}

// OldGroupID returns the old "group_id" field's value of the SeatReservation entity.
// If the SeatReservation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SeatReservationMutation) OldGroupID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGroupID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGroupID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGroupID: %w", err)
	}
	return oldValue.GroupID, nil
}

// ResetGroupID resets all changes to the "group_id" field.
func (m *SeatReservationMutation) ResetGroupID() {
	m.group_id = nil
}

// SetStatus sets the "status" field.
func (m *SeatReservationMutation) SetStatus(crs cinema.SeatReservationStatus) {
	m.status = &crs
	m.addstatus = nil
}

// Status returns the value of the "status" field in the mutation.
func (m *SeatReservationMutation) Status() (r cinema.SeatReservationStatus, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the SeatReservation entity.
// If the SeatReservation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SeatReservationMutation) OldStatus(ctx context.Context) (v cinema.SeatReservationStatus, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// AddStatus adds crs to the "status" field.
func (m *SeatReservationMutation) AddStatus(crs cinema.SeatReservationStatus) {
	if m.addstatus != nil {
		*m.addstatus += crs
	} else {
		m.addstatus = &crs
	}
}

// AddedStatus returns the value that was added to the "status" field in this mutation.
func (m *SeatReservationMutation) AddedStatus() (r cinema.SeatReservationStatus, exists bool) {
	v := m.addstatus
	if v == nil {
		return
	}
	return *v, true
}

// ResetStatus resets all changes to the "status" field.
func (m *SeatReservationMutation) ResetStatus() {
	m.status = nil
	m.addstatus = nil
}

// SetRowNum sets the "row_num" field.
func (m *SeatReservationMutation) SetRowNum(u uint32) {
	m.row_num = &u
	m.addrow_num = nil
}

// RowNum returns the value of the "row_num" field in the mutation.
func (m *SeatReservationMutation) RowNum() (r uint32, exists bool) {
	v := m.row_num
	if v == nil {
		return
	}
	return *v, true
}

// OldRowNum returns the old "row_num" field's value of the SeatReservation entity.
// If the SeatReservation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SeatReservationMutation) OldRowNum(ctx context.Context) (v uint32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRowNum is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRowNum requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRowNum: %w", err)
	}
	return oldValue.RowNum, nil
}

// AddRowNum adds u to the "row_num" field.
func (m *SeatReservationMutation) AddRowNum(u int32) {
	if m.addrow_num != nil {
		*m.addrow_num += u
	} else {
		m.addrow_num = &u
	}
}

// AddedRowNum returns the value that was added to the "row_num" field in this mutation.
func (m *SeatReservationMutation) AddedRowNum() (r int32, exists bool) {
	v := m.addrow_num
	if v == nil {
		return
	}
	return *v, true
}

// ResetRowNum resets all changes to the "row_num" field.
func (m *SeatReservationMutation) ResetRowNum() {
	m.row_num = nil
	m.addrow_num = nil
}

// SetColumnNum sets the "column_num" field.
func (m *SeatReservationMutation) SetColumnNum(u uint32) {
	m.column_num = &u
	m.addcolumn_num = nil
}

// ColumnNum returns the value of the "column_num" field in the mutation.
func (m *SeatReservationMutation) ColumnNum() (r uint32, exists bool) {
	v := m.column_num
	if v == nil {
		return
	}
	return *v, true
}

// OldColumnNum returns the old "column_num" field's value of the SeatReservation entity.
// If the SeatReservation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SeatReservationMutation) OldColumnNum(ctx context.Context) (v uint32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldColumnNum is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldColumnNum requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldColumnNum: %w", err)
	}
	return oldValue.ColumnNum, nil
}

// AddColumnNum adds u to the "column_num" field.
func (m *SeatReservationMutation) AddColumnNum(u int32) {
	if m.addcolumn_num != nil {
		*m.addcolumn_num += u
	} else {
		m.addcolumn_num = &u
	}
}

// AddedColumnNum returns the value that was added to the "column_num" field in this mutation.
func (m *SeatReservationMutation) AddedColumnNum() (r int32, exists bool) {
	v := m.addcolumn_num
	if v == nil {
		return
	}
	return *v, true
}

// ResetColumnNum resets all changes to the "column_num" field.
func (m *SeatReservationMutation) ResetColumnNum() {
	m.column_num = nil
	m.addcolumn_num = nil
}

// SetScreeningID sets the "screening" edge to the Screening entity by id.
func (m *SeatReservationMutation) SetScreeningID(id int64) {
	m.screening = &id
}

// ClearScreening clears the "screening" edge to the Screening entity.
func (m *SeatReservationMutation) ClearScreening() {
	m.clearedscreening = true
}

// ScreeningCleared reports if the "screening" edge to the Screening entity was cleared.
func (m *SeatReservationMutation) ScreeningCleared() bool {
	return m.clearedscreening
}

// ScreeningID returns the "screening" edge ID in the mutation.
func (m *SeatReservationMutation) ScreeningID() (id int64, exists bool) {
	if m.screening != nil {
		return *m.screening, true
	}
	return
}

// ScreeningIDs returns the "screening" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// ScreeningID instead. It exists only for internal usage by the builders.
func (m *SeatReservationMutation) ScreeningIDs() (ids []int64) {
	if id := m.screening; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetScreening resets all changes to the "screening" edge.
func (m *SeatReservationMutation) ResetScreening() {
	m.screening = nil
	m.clearedscreening = false
}

// Where appends a list predicates to the SeatReservationMutation builder.
func (m *SeatReservationMutation) Where(ps ...predicate.SeatReservation) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the SeatReservationMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *SeatReservationMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.SeatReservation, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *SeatReservationMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *SeatReservationMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (SeatReservation).
func (m *SeatReservationMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *SeatReservationMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.created_at != nil {
		fields = append(fields, seatreservation.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, seatreservation.FieldUpdatedAt)
	}
	if m.reserved_at != nil {
		fields = append(fields, seatreservation.FieldReservedAt)
	}
	if m.group_id != nil {
		fields = append(fields, seatreservation.FieldGroupID)
	}
	if m.status != nil {
		fields = append(fields, seatreservation.FieldStatus)
	}
	if m.row_num != nil {
		fields = append(fields, seatreservation.FieldRowNum)
	}
	if m.column_num != nil {
		fields = append(fields, seatreservation.FieldColumnNum)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *SeatReservationMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case seatreservation.FieldCreatedAt:
		return m.CreatedAt()
	case seatreservation.FieldUpdatedAt:
		return m.UpdatedAt()
	case seatreservation.FieldReservedAt:
		return m.ReservedAt()
	case seatreservation.FieldGroupID:
		return m.GroupID()
	case seatreservation.FieldStatus:
		return m.Status()
	case seatreservation.FieldRowNum:
		return m.RowNum()
	case seatreservation.FieldColumnNum:
		return m.ColumnNum()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *SeatReservationMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case seatreservation.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case seatreservation.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case seatreservation.FieldReservedAt:
		return m.OldReservedAt(ctx)
	case seatreservation.FieldGroupID:
		return m.OldGroupID(ctx)
	case seatreservation.FieldStatus:
		return m.OldStatus(ctx)
	case seatreservation.FieldRowNum:
		return m.OldRowNum(ctx)
	case seatreservation.FieldColumnNum:
		return m.OldColumnNum(ctx)
	}
	return nil, fmt.Errorf("unknown SeatReservation field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SeatReservationMutation) SetField(name string, value ent.Value) error {
	switch name {
	case seatreservation.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case seatreservation.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case seatreservation.FieldReservedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetReservedAt(v)
		return nil
	case seatreservation.FieldGroupID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGroupID(v)
		return nil
	case seatreservation.FieldStatus:
		v, ok := value.(cinema.SeatReservationStatus)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case seatreservation.FieldRowNum:
		v, ok := value.(uint32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRowNum(v)
		return nil
	case seatreservation.FieldColumnNum:
		v, ok := value.(uint32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetColumnNum(v)
		return nil
	}
	return fmt.Errorf("unknown SeatReservation field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *SeatReservationMutation) AddedFields() []string {
	var fields []string
	if m.addstatus != nil {
		fields = append(fields, seatreservation.FieldStatus)
	}
	if m.addrow_num != nil {
		fields = append(fields, seatreservation.FieldRowNum)
	}
	if m.addcolumn_num != nil {
		fields = append(fields, seatreservation.FieldColumnNum)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *SeatReservationMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case seatreservation.FieldStatus:
		return m.AddedStatus()
	case seatreservation.FieldRowNum:
		return m.AddedRowNum()
	case seatreservation.FieldColumnNum:
		return m.AddedColumnNum()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SeatReservationMutation) AddField(name string, value ent.Value) error {
	switch name {
	case seatreservation.FieldStatus:
		v, ok := value.(cinema.SeatReservationStatus)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddStatus(v)
		return nil
	case seatreservation.FieldRowNum:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddRowNum(v)
		return nil
	case seatreservation.FieldColumnNum:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddColumnNum(v)
		return nil
	}
	return fmt.Errorf("unknown SeatReservation numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *SeatReservationMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *SeatReservationMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *SeatReservationMutation) ClearField(name string) error {
	return fmt.Errorf("unknown SeatReservation nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *SeatReservationMutation) ResetField(name string) error {
	switch name {
	case seatreservation.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case seatreservation.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case seatreservation.FieldReservedAt:
		m.ResetReservedAt()
		return nil
	case seatreservation.FieldGroupID:
		m.ResetGroupID()
		return nil
	case seatreservation.FieldStatus:
		m.ResetStatus()
		return nil
	case seatreservation.FieldRowNum:
		m.ResetRowNum()
		return nil
	case seatreservation.FieldColumnNum:
		m.ResetColumnNum()
		return nil
	}
	return fmt.Errorf("unknown SeatReservation field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *SeatReservationMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.screening != nil {
		edges = append(edges, seatreservation.EdgeScreening)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *SeatReservationMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case seatreservation.EdgeScreening:
		if id := m.screening; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *SeatReservationMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *SeatReservationMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *SeatReservationMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedscreening {
		edges = append(edges, seatreservation.EdgeScreening)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *SeatReservationMutation) EdgeCleared(name string) bool {
	switch name {
	case seatreservation.EdgeScreening:
		return m.clearedscreening
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *SeatReservationMutation) ClearEdge(name string) error {
	switch name {
	case seatreservation.EdgeScreening:
		m.ClearScreening()
		return nil
	}
	return fmt.Errorf("unknown SeatReservation unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *SeatReservationMutation) ResetEdge(name string) error {
	switch name {
	case seatreservation.EdgeScreening:
		m.ResetScreening()
		return nil
	}
	return fmt.Errorf("unknown SeatReservation edge %s", name)
}
