// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cinema/pkg/ent/cinema"
	"cinema/pkg/ent/movie"
	"cinema/pkg/ent/screening"
	"cinema/pkg/ent/seat"
	"cinema/pkg/ent/seatreservation"
	"cinema/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	cinemaMixin := schema.Cinema{}.Mixin()
	cinemaMixinFields0 := cinemaMixin[0].Fields()
	_ = cinemaMixinFields0
	cinemaFields := schema.Cinema{}.Fields()
	_ = cinemaFields
	// cinemaDescCreatedAt is the schema descriptor for created_at field.
	cinemaDescCreatedAt := cinemaMixinFields0[1].Descriptor()
	// cinema.DefaultCreatedAt holds the default value on creation for the created_at field.
	cinema.DefaultCreatedAt = cinemaDescCreatedAt.Default.(func() time.Time)
	// cinemaDescUpdatedAt is the schema descriptor for updated_at field.
	cinemaDescUpdatedAt := cinemaMixinFields0[2].Descriptor()
	// cinema.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	cinema.DefaultUpdatedAt = cinemaDescUpdatedAt.Default.(func() time.Time)
	// cinema.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	cinema.UpdateDefaultUpdatedAt = cinemaDescUpdatedAt.UpdateDefault.(func() time.Time)
	// cinemaDescNumRow is the schema descriptor for num_row field.
	cinemaDescNumRow := cinemaFields[0].Descriptor()
	// cinema.NumRowValidator is a validator for the "num_row" field. It is called by the builders before save.
	cinema.NumRowValidator = cinemaDescNumRow.Validators[0].(func(uint32) error)
	// cinemaDescNumColumn is the schema descriptor for num_column field.
	cinemaDescNumColumn := cinemaFields[1].Descriptor()
	// cinema.NumColumnValidator is a validator for the "num_column" field. It is called by the builders before save.
	cinema.NumColumnValidator = cinemaDescNumColumn.Validators[0].(func(uint32) error)
	// cinemaDescName is the schema descriptor for name field.
	cinemaDescName := cinemaFields[2].Descriptor()
	// cinema.NameValidator is a validator for the "name" field. It is called by the builders before save.
	cinema.NameValidator = cinemaDescName.Validators[0].(func(string) error)
	// cinemaDescMinDistance is the schema descriptor for min_distance field.
	cinemaDescMinDistance := cinemaFields[3].Descriptor()
	// cinema.MinDistanceValidator is a validator for the "min_distance" field. It is called by the builders before save.
	cinema.MinDistanceValidator = cinemaDescMinDistance.Validators[0].(func(uint32) error)
	movieMixin := schema.Movie{}.Mixin()
	movieMixinFields0 := movieMixin[0].Fields()
	_ = movieMixinFields0
	movieFields := schema.Movie{}.Fields()
	_ = movieFields
	// movieDescCreatedAt is the schema descriptor for created_at field.
	movieDescCreatedAt := movieMixinFields0[1].Descriptor()
	// movie.DefaultCreatedAt holds the default value on creation for the created_at field.
	movie.DefaultCreatedAt = movieDescCreatedAt.Default.(func() time.Time)
	// movieDescUpdatedAt is the schema descriptor for updated_at field.
	movieDescUpdatedAt := movieMixinFields0[2].Descriptor()
	// movie.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	movie.DefaultUpdatedAt = movieDescUpdatedAt.Default.(func() time.Time)
	// movie.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	movie.UpdateDefaultUpdatedAt = movieDescUpdatedAt.UpdateDefault.(func() time.Time)
	// movieDescTitle is the schema descriptor for title field.
	movieDescTitle := movieFields[0].Descriptor()
	// movie.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	movie.TitleValidator = movieDescTitle.Validators[0].(func(string) error)
	screeningMixin := schema.Screening{}.Mixin()
	screeningMixinFields0 := screeningMixin[0].Fields()
	_ = screeningMixinFields0
	screeningFields := schema.Screening{}.Fields()
	_ = screeningFields
	// screeningDescCreatedAt is the schema descriptor for created_at field.
	screeningDescCreatedAt := screeningMixinFields0[1].Descriptor()
	// screening.DefaultCreatedAt holds the default value on creation for the created_at field.
	screening.DefaultCreatedAt = screeningDescCreatedAt.Default.(func() time.Time)
	// screeningDescUpdatedAt is the schema descriptor for updated_at field.
	screeningDescUpdatedAt := screeningMixinFields0[2].Descriptor()
	// screening.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	screening.DefaultUpdatedAt = screeningDescUpdatedAt.Default.(func() time.Time)
	// screening.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	screening.UpdateDefaultUpdatedAt = screeningDescUpdatedAt.UpdateDefault.(func() time.Time)
	// screeningDescTitle is the schema descriptor for title field.
	screeningDescTitle := screeningFields[0].Descriptor()
	// screening.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	screening.TitleValidator = screeningDescTitle.Validators[0].(func(string) error)
	// screeningDescMinDistance is the schema descriptor for min_distance field.
	screeningDescMinDistance := screeningFields[2].Descriptor()
	// screening.MinDistanceValidator is a validator for the "min_distance" field. It is called by the builders before save.
	screening.MinDistanceValidator = screeningDescMinDistance.Validators[0].(func(int32) error)
	seatMixin := schema.Seat{}.Mixin()
	seatMixinFields0 := seatMixin[0].Fields()
	_ = seatMixinFields0
	seatFields := schema.Seat{}.Fields()
	_ = seatFields
	// seatDescCreatedAt is the schema descriptor for created_at field.
	seatDescCreatedAt := seatMixinFields0[1].Descriptor()
	// seat.DefaultCreatedAt holds the default value on creation for the created_at field.
	seat.DefaultCreatedAt = seatDescCreatedAt.Default.(func() time.Time)
	// seatDescUpdatedAt is the schema descriptor for updated_at field.
	seatDescUpdatedAt := seatMixinFields0[2].Descriptor()
	// seat.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	seat.DefaultUpdatedAt = seatDescUpdatedAt.Default.(func() time.Time)
	// seat.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	seat.UpdateDefaultUpdatedAt = seatDescUpdatedAt.UpdateDefault.(func() time.Time)
	// seatDescRow is the schema descriptor for row field.
	seatDescRow := seatFields[0].Descriptor()
	// seat.RowValidator is a validator for the "row" field. It is called by the builders before save.
	seat.RowValidator = seatDescRow.Validators[0].(func(int16) error)
	// seatDescColumn is the schema descriptor for column field.
	seatDescColumn := seatFields[1].Descriptor()
	// seat.ColumnValidator is a validator for the "column" field. It is called by the builders before save.
	seat.ColumnValidator = seatDescColumn.Validators[0].(func(int16) error)
	seatreservationMixin := schema.SeatReservation{}.Mixin()
	seatreservationMixinFields0 := seatreservationMixin[0].Fields()
	_ = seatreservationMixinFields0
	seatreservationFields := schema.SeatReservation{}.Fields()
	_ = seatreservationFields
	// seatreservationDescCreatedAt is the schema descriptor for created_at field.
	seatreservationDescCreatedAt := seatreservationMixinFields0[1].Descriptor()
	// seatreservation.DefaultCreatedAt holds the default value on creation for the created_at field.
	seatreservation.DefaultCreatedAt = seatreservationDescCreatedAt.Default.(func() time.Time)
	// seatreservationDescUpdatedAt is the schema descriptor for updated_at field.
	seatreservationDescUpdatedAt := seatreservationMixinFields0[2].Descriptor()
	// seatreservation.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	seatreservation.DefaultUpdatedAt = seatreservationDescUpdatedAt.Default.(func() time.Time)
	// seatreservation.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	seatreservation.UpdateDefaultUpdatedAt = seatreservationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// seatreservationDescReservedAt is the schema descriptor for reserved_at field.
	seatreservationDescReservedAt := seatreservationFields[0].Descriptor()
	// seatreservation.DefaultReservedAt holds the default value on creation for the reserved_at field.
	seatreservation.DefaultReservedAt = seatreservationDescReservedAt.Default.(func() time.Time)
	// seatreservationDescStartTime is the schema descriptor for start_time field.
	seatreservationDescStartTime := seatreservationFields[3].Descriptor()
	// seatreservation.DefaultStartTime holds the default value on creation for the start_time field.
	seatreservation.DefaultStartTime = seatreservationDescStartTime.Default.(func() time.Time)
	// seatreservationDescEndTime is the schema descriptor for end_time field.
	seatreservationDescEndTime := seatreservationFields[4].Descriptor()
	// seatreservation.DefaultEndTime holds the default value on creation for the end_time field.
	seatreservation.DefaultEndTime = seatreservationDescEndTime.Default.(time.Time)
}
