// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cinema/pkg/ent/predicate"
	"cinema/pkg/ent/screening"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ScreeningDelete is the builder for deleting a Screening entity.
type ScreeningDelete struct {
	config
	hooks    []Hook
	mutation *ScreeningMutation
}

// Where appends a list predicates to the ScreeningDelete builder.
func (sd *ScreeningDelete) Where(ps ...predicate.Screening) *ScreeningDelete {
	sd.mutation.Where(ps...)
	return sd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sd *ScreeningDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, sd.sqlExec, sd.mutation, sd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sd *ScreeningDelete) ExecX(ctx context.Context) int {
	n, err := sd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sd *ScreeningDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(screening.Table, sqlgraph.NewFieldSpec(screening.FieldID, field.TypeInt64))
	if ps := sd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sd.mutation.done = true
	return affected, err
}

// ScreeningDeleteOne is the builder for deleting a single Screening entity.
type ScreeningDeleteOne struct {
	sd *ScreeningDelete
}

// Where appends a list predicates to the ScreeningDelete builder.
func (sdo *ScreeningDeleteOne) Where(ps ...predicate.Screening) *ScreeningDeleteOne {
	sdo.sd.mutation.Where(ps...)
	return sdo
}

// Exec executes the deletion query.
func (sdo *ScreeningDeleteOne) Exec(ctx context.Context) error {
	n, err := sdo.sd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{screening.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sdo *ScreeningDeleteOne) ExecX(ctx context.Context) {
	if err := sdo.Exec(ctx); err != nil {
		panic(err)
	}
}
