// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cinema/pkg/ent/predicate"
	"cinema/pkg/ent/seatreservation"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SeatReservationDelete is the builder for deleting a SeatReservation entity.
type SeatReservationDelete struct {
	config
	hooks    []Hook
	mutation *SeatReservationMutation
}

// Where appends a list predicates to the SeatReservationDelete builder.
func (srd *SeatReservationDelete) Where(ps ...predicate.SeatReservation) *SeatReservationDelete {
	srd.mutation.Where(ps...)
	return srd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (srd *SeatReservationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, srd.sqlExec, srd.mutation, srd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (srd *SeatReservationDelete) ExecX(ctx context.Context) int {
	n, err := srd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (srd *SeatReservationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(seatreservation.Table, sqlgraph.NewFieldSpec(seatreservation.FieldID, field.TypeInt64))
	if ps := srd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, srd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	srd.mutation.done = true
	return affected, err
}

// SeatReservationDeleteOne is the builder for deleting a single SeatReservation entity.
type SeatReservationDeleteOne struct {
	srd *SeatReservationDelete
}

// Where appends a list predicates to the SeatReservationDelete builder.
func (srdo *SeatReservationDeleteOne) Where(ps ...predicate.SeatReservation) *SeatReservationDeleteOne {
	srdo.srd.mutation.Where(ps...)
	return srdo
}

// Exec executes the deletion query.
func (srdo *SeatReservationDeleteOne) Exec(ctx context.Context) error {
	n, err := srdo.srd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{seatreservation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (srdo *SeatReservationDeleteOne) ExecX(ctx context.Context) {
	if err := srdo.Exec(ctx); err != nil {
		panic(err)
	}
}
