// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cinema/pkg/ent/cinema"
	"cinema/pkg/ent/seat"
	"cinema/pkg/ent/seatreservation"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SeatCreate is the builder for creating a Seat entity.
type SeatCreate struct {
	config
	mutation *SeatMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (sc *SeatCreate) SetCreatedAt(t time.Time) *SeatCreate {
	sc.mutation.SetCreatedAt(t)
	return sc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sc *SeatCreate) SetNillableCreatedAt(t *time.Time) *SeatCreate {
	if t != nil {
		sc.SetCreatedAt(*t)
	}
	return sc
}

// SetUpdatedAt sets the "updated_at" field.
func (sc *SeatCreate) SetUpdatedAt(t time.Time) *SeatCreate {
	sc.mutation.SetUpdatedAt(t)
	return sc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (sc *SeatCreate) SetNillableUpdatedAt(t *time.Time) *SeatCreate {
	if t != nil {
		sc.SetUpdatedAt(*t)
	}
	return sc
}

// SetRow sets the "row" field.
func (sc *SeatCreate) SetRow(i int16) *SeatCreate {
	sc.mutation.SetRow(i)
	return sc
}

// SetColumn sets the "column" field.
func (sc *SeatCreate) SetColumn(i int16) *SeatCreate {
	sc.mutation.SetColumn(i)
	return sc
}

// SetID sets the "id" field.
func (sc *SeatCreate) SetID(i int64) *SeatCreate {
	sc.mutation.SetID(i)
	return sc
}

// SetCinemaID sets the "cinema" edge to the Cinema entity by ID.
func (sc *SeatCreate) SetCinemaID(id int64) *SeatCreate {
	sc.mutation.SetCinemaID(id)
	return sc
}

// SetNillableCinemaID sets the "cinema" edge to the Cinema entity by ID if the given value is not nil.
func (sc *SeatCreate) SetNillableCinemaID(id *int64) *SeatCreate {
	if id != nil {
		sc = sc.SetCinemaID(*id)
	}
	return sc
}

// SetCinema sets the "cinema" edge to the Cinema entity.
func (sc *SeatCreate) SetCinema(c *Cinema) *SeatCreate {
	return sc.SetCinemaID(c.ID)
}

// AddSeatReservationIDs adds the "seat_reservations" edge to the SeatReservation entity by IDs.
func (sc *SeatCreate) AddSeatReservationIDs(ids ...int64) *SeatCreate {
	sc.mutation.AddSeatReservationIDs(ids...)
	return sc
}

// AddSeatReservations adds the "seat_reservations" edges to the SeatReservation entity.
func (sc *SeatCreate) AddSeatReservations(s ...*SeatReservation) *SeatCreate {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return sc.AddSeatReservationIDs(ids...)
}

// Mutation returns the SeatMutation object of the builder.
func (sc *SeatCreate) Mutation() *SeatMutation {
	return sc.mutation
}

// Save creates the Seat in the database.
func (sc *SeatCreate) Save(ctx context.Context) (*Seat, error) {
	sc.defaults()
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SeatCreate) SaveX(ctx context.Context) *Seat {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SeatCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SeatCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *SeatCreate) defaults() {
	if _, ok := sc.mutation.CreatedAt(); !ok {
		v := seat.DefaultCreatedAt()
		sc.mutation.SetCreatedAt(v)
	}
	if _, ok := sc.mutation.UpdatedAt(); !ok {
		v := seat.DefaultUpdatedAt()
		sc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SeatCreate) check() error {
	if _, ok := sc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Seat.created_at"`)}
	}
	if _, ok := sc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Seat.updated_at"`)}
	}
	if _, ok := sc.mutation.Row(); !ok {
		return &ValidationError{Name: "row", err: errors.New(`ent: missing required field "Seat.row"`)}
	}
	if v, ok := sc.mutation.Row(); ok {
		if err := seat.RowValidator(v); err != nil {
			return &ValidationError{Name: "row", err: fmt.Errorf(`ent: validator failed for field "Seat.row": %w`, err)}
		}
	}
	if _, ok := sc.mutation.Column(); !ok {
		return &ValidationError{Name: "column", err: errors.New(`ent: missing required field "Seat.column"`)}
	}
	if v, ok := sc.mutation.Column(); ok {
		if err := seat.ColumnValidator(v); err != nil {
			return &ValidationError{Name: "column", err: fmt.Errorf(`ent: validator failed for field "Seat.column": %w`, err)}
		}
	}
	return nil
}

func (sc *SeatCreate) sqlSave(ctx context.Context) (*Seat, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *SeatCreate) createSpec() (*Seat, *sqlgraph.CreateSpec) {
	var (
		_node = &Seat{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(seat.Table, sqlgraph.NewFieldSpec(seat.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = sc.conflict
	if id, ok := sc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := sc.mutation.CreatedAt(); ok {
		_spec.SetField(seat.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := sc.mutation.UpdatedAt(); ok {
		_spec.SetField(seat.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := sc.mutation.Row(); ok {
		_spec.SetField(seat.FieldRow, field.TypeInt16, value)
		_node.Row = value
	}
	if value, ok := sc.mutation.Column(); ok {
		_spec.SetField(seat.FieldColumn, field.TypeInt16, value)
		_node.Column = value
	}
	if nodes := sc.mutation.CinemaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   seat.CinemaTable,
			Columns: []string{seat.CinemaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cinema.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.cinema_seats = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.SeatReservationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seat.SeatReservationsTable,
			Columns: []string{seat.SeatReservationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seatreservation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Seat.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SeatUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (sc *SeatCreate) OnConflict(opts ...sql.ConflictOption) *SeatUpsertOne {
	sc.conflict = opts
	return &SeatUpsertOne{
		create: sc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Seat.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (sc *SeatCreate) OnConflictColumns(columns ...string) *SeatUpsertOne {
	sc.conflict = append(sc.conflict, sql.ConflictColumns(columns...))
	return &SeatUpsertOne{
		create: sc,
	}
}

type (
	// SeatUpsertOne is the builder for "upsert"-ing
	//  one Seat node.
	SeatUpsertOne struct {
		create *SeatCreate
	}

	// SeatUpsert is the "OnConflict" setter.
	SeatUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SeatUpsert) SetUpdatedAt(v time.Time) *SeatUpsert {
	u.Set(seat.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SeatUpsert) UpdateUpdatedAt() *SeatUpsert {
	u.SetExcluded(seat.FieldUpdatedAt)
	return u
}

// SetRow sets the "row" field.
func (u *SeatUpsert) SetRow(v int16) *SeatUpsert {
	u.Set(seat.FieldRow, v)
	return u
}

// UpdateRow sets the "row" field to the value that was provided on create.
func (u *SeatUpsert) UpdateRow() *SeatUpsert {
	u.SetExcluded(seat.FieldRow)
	return u
}

// AddRow adds v to the "row" field.
func (u *SeatUpsert) AddRow(v int16) *SeatUpsert {
	u.Add(seat.FieldRow, v)
	return u
}

// SetColumn sets the "column" field.
func (u *SeatUpsert) SetColumn(v int16) *SeatUpsert {
	u.Set(seat.FieldColumn, v)
	return u
}

// UpdateColumn sets the "column" field to the value that was provided on create.
func (u *SeatUpsert) UpdateColumn() *SeatUpsert {
	u.SetExcluded(seat.FieldColumn)
	return u
}

// AddColumn adds v to the "column" field.
func (u *SeatUpsert) AddColumn(v int16) *SeatUpsert {
	u.Add(seat.FieldColumn, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Seat.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(seat.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SeatUpsertOne) UpdateNewValues() *SeatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(seat.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(seat.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Seat.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SeatUpsertOne) Ignore() *SeatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SeatUpsertOne) DoNothing() *SeatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SeatCreate.OnConflict
// documentation for more info.
func (u *SeatUpsertOne) Update(set func(*SeatUpsert)) *SeatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SeatUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SeatUpsertOne) SetUpdatedAt(v time.Time) *SeatUpsertOne {
	return u.Update(func(s *SeatUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SeatUpsertOne) UpdateUpdatedAt() *SeatUpsertOne {
	return u.Update(func(s *SeatUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetRow sets the "row" field.
func (u *SeatUpsertOne) SetRow(v int16) *SeatUpsertOne {
	return u.Update(func(s *SeatUpsert) {
		s.SetRow(v)
	})
}

// AddRow adds v to the "row" field.
func (u *SeatUpsertOne) AddRow(v int16) *SeatUpsertOne {
	return u.Update(func(s *SeatUpsert) {
		s.AddRow(v)
	})
}

// UpdateRow sets the "row" field to the value that was provided on create.
func (u *SeatUpsertOne) UpdateRow() *SeatUpsertOne {
	return u.Update(func(s *SeatUpsert) {
		s.UpdateRow()
	})
}

// SetColumn sets the "column" field.
func (u *SeatUpsertOne) SetColumn(v int16) *SeatUpsertOne {
	return u.Update(func(s *SeatUpsert) {
		s.SetColumn(v)
	})
}

// AddColumn adds v to the "column" field.
func (u *SeatUpsertOne) AddColumn(v int16) *SeatUpsertOne {
	return u.Update(func(s *SeatUpsert) {
		s.AddColumn(v)
	})
}

// UpdateColumn sets the "column" field to the value that was provided on create.
func (u *SeatUpsertOne) UpdateColumn() *SeatUpsertOne {
	return u.Update(func(s *SeatUpsert) {
		s.UpdateColumn()
	})
}

// Exec executes the query.
func (u *SeatUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SeatCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SeatUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SeatUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SeatUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SeatCreateBulk is the builder for creating many Seat entities in bulk.
type SeatCreateBulk struct {
	config
	err      error
	builders []*SeatCreate
	conflict []sql.ConflictOption
}

// Save creates the Seat entities in the database.
func (scb *SeatCreateBulk) Save(ctx context.Context) ([]*Seat, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Seat, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SeatMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = scb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SeatCreateBulk) SaveX(ctx context.Context) []*Seat {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SeatCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SeatCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Seat.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SeatUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (scb *SeatCreateBulk) OnConflict(opts ...sql.ConflictOption) *SeatUpsertBulk {
	scb.conflict = opts
	return &SeatUpsertBulk{
		create: scb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Seat.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (scb *SeatCreateBulk) OnConflictColumns(columns ...string) *SeatUpsertBulk {
	scb.conflict = append(scb.conflict, sql.ConflictColumns(columns...))
	return &SeatUpsertBulk{
		create: scb,
	}
}

// SeatUpsertBulk is the builder for "upsert"-ing
// a bulk of Seat nodes.
type SeatUpsertBulk struct {
	create *SeatCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Seat.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(seat.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SeatUpsertBulk) UpdateNewValues() *SeatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(seat.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(seat.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Seat.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SeatUpsertBulk) Ignore() *SeatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SeatUpsertBulk) DoNothing() *SeatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SeatCreateBulk.OnConflict
// documentation for more info.
func (u *SeatUpsertBulk) Update(set func(*SeatUpsert)) *SeatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SeatUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SeatUpsertBulk) SetUpdatedAt(v time.Time) *SeatUpsertBulk {
	return u.Update(func(s *SeatUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SeatUpsertBulk) UpdateUpdatedAt() *SeatUpsertBulk {
	return u.Update(func(s *SeatUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetRow sets the "row" field.
func (u *SeatUpsertBulk) SetRow(v int16) *SeatUpsertBulk {
	return u.Update(func(s *SeatUpsert) {
		s.SetRow(v)
	})
}

// AddRow adds v to the "row" field.
func (u *SeatUpsertBulk) AddRow(v int16) *SeatUpsertBulk {
	return u.Update(func(s *SeatUpsert) {
		s.AddRow(v)
	})
}

// UpdateRow sets the "row" field to the value that was provided on create.
func (u *SeatUpsertBulk) UpdateRow() *SeatUpsertBulk {
	return u.Update(func(s *SeatUpsert) {
		s.UpdateRow()
	})
}

// SetColumn sets the "column" field.
func (u *SeatUpsertBulk) SetColumn(v int16) *SeatUpsertBulk {
	return u.Update(func(s *SeatUpsert) {
		s.SetColumn(v)
	})
}

// AddColumn adds v to the "column" field.
func (u *SeatUpsertBulk) AddColumn(v int16) *SeatUpsertBulk {
	return u.Update(func(s *SeatUpsert) {
		s.AddColumn(v)
	})
}

// UpdateColumn sets the "column" field to the value that was provided on create.
func (u *SeatUpsertBulk) UpdateColumn() *SeatUpsertBulk {
	return u.Update(func(s *SeatUpsert) {
		s.UpdateColumn()
	})
}

// Exec executes the query.
func (u *SeatUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SeatCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SeatCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SeatUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
