// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cinema/pkg/ent/cinema"
	"cinema/pkg/ent/seat"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Seat is the model entity for the Seat schema.
type Seat struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Row holds the value of the "row" field.
	Row int16 `json:"row,omitempty"`
	// Column holds the value of the "column" field.
	Column int16 `json:"column,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SeatQuery when eager-loading is set.
	Edges        SeatEdges `json:"edges"`
	cinema_seats *int64
	selectValues sql.SelectValues
}

// SeatEdges holds the relations/edges for other nodes in the graph.
type SeatEdges struct {
	// Cinema holds the value of the cinema edge.
	Cinema *Cinema `json:"cinema,omitempty"`
	// SeatReservations holds the value of the seat_reservations edge.
	SeatReservations []*SeatReservation `json:"seat_reservations,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// CinemaOrErr returns the Cinema value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SeatEdges) CinemaOrErr() (*Cinema, error) {
	if e.Cinema != nil {
		return e.Cinema, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: cinema.Label}
	}
	return nil, &NotLoadedError{edge: "cinema"}
}

// SeatReservationsOrErr returns the SeatReservations value or an error if the edge
// was not loaded in eager-loading.
func (e SeatEdges) SeatReservationsOrErr() ([]*SeatReservation, error) {
	if e.loadedTypes[1] {
		return e.SeatReservations, nil
	}
	return nil, &NotLoadedError{edge: "seat_reservations"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Seat) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case seat.FieldID, seat.FieldRow, seat.FieldColumn:
			values[i] = new(sql.NullInt64)
		case seat.FieldCreatedAt, seat.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case seat.ForeignKeys[0]: // cinema_seats
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Seat fields.
func (s *Seat) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case seat.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			s.ID = int64(value.Int64)
		case seat.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				s.CreatedAt = value.Time
			}
		case seat.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				s.UpdatedAt = value.Time
			}
		case seat.FieldRow:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field row", values[i])
			} else if value.Valid {
				s.Row = int16(value.Int64)
			}
		case seat.FieldColumn:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field column", values[i])
			} else if value.Valid {
				s.Column = int16(value.Int64)
			}
		case seat.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field cinema_seats", value)
			} else if value.Valid {
				s.cinema_seats = new(int64)
				*s.cinema_seats = int64(value.Int64)
			}
		default:
			s.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Seat.
// This includes values selected through modifiers, order, etc.
func (s *Seat) Value(name string) (ent.Value, error) {
	return s.selectValues.Get(name)
}

// QueryCinema queries the "cinema" edge of the Seat entity.
func (s *Seat) QueryCinema() *CinemaQuery {
	return NewSeatClient(s.config).QueryCinema(s)
}

// QuerySeatReservations queries the "seat_reservations" edge of the Seat entity.
func (s *Seat) QuerySeatReservations() *SeatReservationQuery {
	return NewSeatClient(s.config).QuerySeatReservations(s)
}

// Update returns a builder for updating this Seat.
// Note that you need to call Seat.Unwrap() before calling this method if this Seat
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Seat) Update() *SeatUpdateOne {
	return NewSeatClient(s.config).UpdateOne(s)
}

// Unwrap unwraps the Seat entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Seat) Unwrap() *Seat {
	_tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Seat is not a transactional entity")
	}
	s.config.driver = _tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Seat) String() string {
	var builder strings.Builder
	builder.WriteString("Seat(")
	builder.WriteString(fmt.Sprintf("id=%v, ", s.ID))
	builder.WriteString("created_at=")
	builder.WriteString(s.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(s.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("row=")
	builder.WriteString(fmt.Sprintf("%v", s.Row))
	builder.WriteString(", ")
	builder.WriteString("column=")
	builder.WriteString(fmt.Sprintf("%v", s.Column))
	builder.WriteByte(')')
	return builder.String()
}

// Seats is a parsable slice of Seat.
type Seats []*Seat
