// Code generated by mykit. DO NOT EDIT.
// Version (devel)

package client

import (
	carbon "cinema/pkg/config"
	client "cinema/pkg/grpc"
	"google.golang.org/grpc"

	pb "cinema/api"
)

type BackofficeCinemaClient struct {
	pb.BackofficeCinemaClient
}

func NewBackofficeCinemaClient(config *carbon.TCPSocket, options ...grpc.DialOption) (*BackofficeCinemaClient, error) {
	conn, err := client.NewClientConnection(config, options...)
	if err != nil {
		return nil, err
	}
	return &BackofficeCinemaClient{
		BackofficeCinemaClient: pb.NewBackofficeCinemaClient(conn),
	}, nil
}
