// Code generated by mykit. DO NOT EDIT.
// Version (devel)

package client

import (
	carbon "cinema/pkg/config"
	client "cinema/pkg/grpc"
	"google.golang.org/grpc"

	pb "cinema/api"
)

type CinemaClient struct {
	pb.CinemaClient
}

func NewCinemaClient(config *carbon.TCPSocket, options ...grpc.DialOption) (*CinemaClient, error) {
	conn, err := client.NewClientConnection(config, options...)
	if err != nil {
		return nil, err
	}
	return &CinemaClient{
		CinemaClient: pb.NewCinemaClient(conn),
	}, nil
}
